skill_patterns = [
    [{"LOWER": "python"}],
    [{"LOWER": "javascript"}],
    [{"LOWER": "java"}],
    [{"LOWER": "c++"}],
    [{"LOWER": "c#"}],
    [{"LOWER": "ruby"}],
    [{"LOWER": "php"}],
    [{"LOWER": "swift"}],
    [{"LOWER": "kotlin"}],
    [{"LOWER": "sql"}],
    [{"LOWER": "html"}],
    [{"LOWER": "css"}],
    [{"LOWER": "react"}],
    [{"LOWER": "angular"}],
    [{"LOWER": "vue"}],
    [{"LOWER": "django"}],
    [{"LOWER": "flask"}],
    [{"LOWER": "node.js"}],
    [{"LOWER": "express"}],
    [{"LOWER": "spring"}],
    [{"LOWER": "tensorflow"}],
    [{"LOWER": "pytorch"}],
    [{"LOWER": "keras"}],
    [{"LOWER": "docker"}],
    [{"LOWER": "kubernetes"}],
    [{"LOWER": "aws"}],
    [{"LOWER": "azure"}],
    [{"LOWER": "gcp"}],
    [{"LOWER": "git"}],
    [{"LOWER": "jira"}],
    [{"LOWER": "agile"}],
    [{"LOWER": "scrum"}],
    [{"LOWER": "communication"}],
    [{"LOWER": "leadership"}],
    [{"LOWER": "problem-solving"}],
    [{"LOWER": "time management"}],
    [{"LOWER": "critical thinking"}],
    [{"LOWER": "teamwork"}],
    [{"LOWER": "adaptability"}],
    [{"LOWER": "creativity"}],
    [{"LOWER": "emotional intelligence"}],
    [{"LOWER": "empathy"}],
    [{"LOWER": "stress management"}],
    [{"LOWER": "conflict resolution"}],
    [{"LOWER": "negotiation"}],
    [{"LOWER": "decision making"}],
    [{"LOWER": "active listening"}],
    [{"LOWER": "motivation"}],
    [{"LOWER": "persistence"}],
    [{"LOWER": "firebase"}],
    [{"LOWER": "mongodb"}],
    [{"LOWER": "mysql"}],
    [{"LOWER": "postgresql"}],
    [{"LOWER": "redis"}],
    [{"LOWER": "elasticsearch"}],
    [{"LOWER": "rest"}],
    [{"LOWER": "graphql"}],
    [{"LOWER": "api"}],
    [{"LOWER": "oauth"}],
    [{"LOWER": "jwt"}],
    [{"LOWER": "linux"}],
    [{"LOWER": "windows"}],
    [{"LOWER": "macos"}],
    [{"LOWER": "android"}],
    [{"LOWER": "ios"}],
    [{"LOWER": "raspberry pi"}],
    [{"LOWER": "arduino"}],
    [{"LOWER": "rasa"}],
    [{"LOWER": "dialogflow"}],
    [{"LOWER": "wit.ai"}],
    [{"LOWER": "ibm watson"}],
    [{"LOWER": "microsoft luis"}],
    [{"LOWER": "alexa"}],
    [{"LOWER": "google assistant"}],
    [{"LOWER": "chatfuel"}],
    [{"LOWER": "manychat"}],
    [{"LOWER": "twilio"}],
    [{"LOWER": "microsoft teams"}],
    [{"LOWER": "zoom"}],
    [{"LOWER": "webex"}],
    [{"LOWER": "skype"}],
    [{"LOWER": "microsoft office"}],
    [{"LOWER": "google workspace"}],
    [{"LOWER": "trello"}],
    [{"LOWER": "asana"}],
    [{"LOWER": "notion"}],
    [{"LOWER": "airtable"}],
    [{"LOWER": "salesforce"}],
    [{"LOWER": "hubspot"}],
    [{"LOWER": "zendesk"}],
    [{"LOWER": "intercom"}],
    [{"LOWER": "freshdesk"}],
    [{"LOWER": "jira service desk"}],
    [{"LOWER": "servicenow"}],
    [{"LOWER": "cisco"}],
    [{"LOWER": "netapp"}],
    [{"LOWER": "vmware"}],
    [{"LOWER": "citrix"}],
    [{"LOWER": "hpe"}],
    [{"LOWER": "dell"}],
    [{"LOWER": "lenovo"}],
    [{"LOWER": "samsung"}],
    [{"LOWER": "apple"}],
    [{"LOWER": "microsoft"}],
    [{"LOWER": "sony"}],
    [{"LOWER": "dart"}],
    [{"LOWER": "flutter"}],
    [{"LOWER": "xamarin"}],
    [{"LOWER": "ionic"}],
    [{"LOWER": "react native"}],
    [{"LOWER": "native script"}],
    [{"LOWER": "phonegap"}],
    [{"LOWER": "cordova"}],
    [{"LOWER": "swiftui"}],
    [{"LOWER": "objective-c"}],
    [{"LOWER": "kotlin native"}],
    [{"LOWER": "java fx"}],
    [{"LOWER": "javafx"}],
    [{"LOWER": "swing"}],
    [{"LOWER": "awt"}],
    [{"LOWER": "junit"}],
    [{"LOWER": "testng"}],
    [{"LOWER": "mockito"}],
    [{"LOWER": "cucumber"}],
    [{"LOWER": "selenium"}],
    [{"LOWER": "appium"}],
    [{"LOWER": "jmeter"}],
    [{"LOWER": "loadrunner"}],
    [{"LOWER": "postman"}],
    [{"LOWER": "newman"}],
    [{"LOWER": "k6"}],
    [{"LOWER": "locust"}],
    [{"LOWER": "next.js"}],
    [{"LOWER": "nuxt.js"}],
    [{"LOWER": "svelte"}],
    [{"LOWER": "gatsby"}],
    [{"LOWER": "hugo"}],
    [{"LOWER": "jekyll"}],
    [{"LOWER": "wordpress"}],
    [{"LOWER": "drupal"}],
    [{"LOWER": "joomla"}],
    [{"LOWER": "magento"}],
    [{"LOWER": "shopify"}],
    [{"LOWER": "woocommerce"}],
    [{"LOWER": "bigcommerce"}],
    [{"LOWER": "prestashop"}],
    [{"LOWER": "opencart"}],
    [{"LOWER": "oscommerce"}],
    [{"LOWER": "volusion"}],
    [{"LOWER": "wix"}],
    [{"LOWER": "weebly"}],
    [{"LOWER": "squarespace"}],
    [{"LOWER": "webflow"}],
    [{"LOWER": "elementor"}],
    [{"LOWER": "divi"}],
    [{"LOWER": "beaver builder"}],
    [{"LOWER": "visual composer"}],
    [{"LOWER": "brizy"}],
    [{"LOWER": "oxygen"}],
    [{"LOWER": "accounting"}],
    [{"LOWER": "finance"}],
    [{"LOWER": "economics"}],
    [{"LOWER": "budgeting"}],
    [{"LOWER": "forecasting"}],
    [{"LOWER": "excel"}],
    [{"LOWER": "quickbooks"}],
    [{"LOWER": "sap"}],
    [{"LOWER": "financial analysis"}],
    [{"LOWER": "auditing"}],
    [{"LOWER": "seo"}],
    [{"LOWER": "sem"}],
    [{"LOWER": "digital marketing"}],
    [{"LOWER": "content marketing"}],
    [{"LOWER": "social media"}],
    [{"LOWER": "branding"}],
    [{"LOWER": "public relations"}],
    [{"LOWER": "copywriting"}],
    [{"LOWER": "google analytics"}],
    [{"LOWER": "crm"}],
    [{"LOWER": "graphic design"}],
    [{"LOWER": "ux/ui design"}],
    [{"LOWER": "adobe photoshop"}],
    [{"LOWER": "adobe illustrator"}],
    [{"LOWER": "indesign"}],
    [{"LOWER": "sketch"}],
    [{"LOWER": "figma"}],
    [{"LOWER": "photography"}],
    [{"LOWER": "videography"}],
    [{"LOWER": "patient care"}],
    [{"LOWER": "medical knowledge"}],
    [{"LOWER": "emergency response"}],
    [{"LOWER": "clinical skills"}],
    [{"LOWER": "diagnosis"}],
    [{"LOWER": "recruitment"}],
    [{"LOWER": "talent management"}],
    [{"LOWER": "employee relations"}],
    [{"LOWER": "performance management"}],
    [{"LOWER": "hr policies"}],
    [{"LOWER": "legal research"}],
    [{"LOWER": "contract law"}],
    [{"LOWER": "litigation"}],
    [{"LOWER": "compliance"}],
    [{"LOWER": "intellectual property"}],
    [{"LOWER": "curriculum development"}],
    [{"LOWER": "educational leadership"}],
    [{"LOWER": "classroom management"}],
    [{"LOWER": "e-learning"}],
    [{"LOWER": "student assessment"}],
]
